# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='start_time',
        ),
    ]
